### ISSUE TITLE
inserters don't work

### ISSUE THREAD

**Issue by fpvandoorn** [exfret/factorio-property-randomizer-mod#1]
I started a game with inserters randomized, but none of my inserters picks up anything. If I manually give an inserter an item, then it doesn't drop it off (the robotic hand also does not move to the drop-off indicated by the yellow arrow). 

I made sure the inserters have power/fuel.

v0.2.1

screenshot:
<img width="373" alt="image" src="https://github.com/exfret/factorio-property-randomizer-mod/assets/7376012/74e90726-95e6-40f0-8cc9-4d4ab95924b1">

[save file](https://github.com/exfret/factorio-property-randomizer-mod/files/14467016/_autosave1.zip)

**Comment by exfret** [comment]
Can I have a screenshot of your startup settings? Thanks so much for the report.

Also, I really need to update this github lol.

**Comment by fpvandoorn** [comment]
<img width="505" alt="image" src="https://github.com/exfret/factorio-property-randomizer-mod/assets/7376012/8cb11be5-380b-468d-ab92-4f106a415adb">

**Comment by exfret** [comment]
Thanks! I wouldn't have narrowed down the issue without your help. I found the issue... if the inserter extension speed (which is different from rotation speed and usually hidden) is lower than 1/256 of a tile per tick, which is the minimum unit of distance in factorio, it isn't just slow, but rather it doesn't move at all! I set a minimum value of 1/100, which actually isn't all that slow either.

**Comment by exfret** [comment]
The new update should fix this. Let me know if it doesn't work.

**Comment by fpvandoorn** [comment]
Nice. It works now!
